# Generated by Django 4.1.2 on 2023-05-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated', '-date_added'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='introText',
            new_name='intro_text',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='socialLinks',
            new_name='social_links',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='activitiesAndSocieties',
            new_name='activities_societies',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='endYear',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='schoolName',
            new_name='school_name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='startYear',
            new_name='start_year',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='aboutCompany',
            new_name='about_company',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='endYear',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='experiences',
            old_name='startYear',
            new_name='start_year',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='aboutProject',
            new_name='about_project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='dateAdded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='livePreview',
            new_name='live_preview',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectName',
            new_name='project_name',
        ),
    ]
