# Generated by Django 4.1.2 on 2023-05-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='school_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
